### ISSUE TITLE
[p]wordletop throws error when empty

### ISSUE THREAD

**Issue by jakehlee** [jakehlee/JDG-Cogs-V3#13]
```
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]: [2023-03-20 21:23:53] [ERROR] red: Exception in command 'wordletop'
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]: Traceback (most recent call last):
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]:   File "/home/jake/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]:     ret = await coro(*args, **kwargs)
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]:   File "/home/jake/repos/JDG-Cogs-V3/wordle/wordle.py", line 185, in wordletop
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]:     avgboard += f"{prefixes[i]} {ctx.guild.get_member(avg_attempts[i]['member']).mention} ({avg_attempts[i]['avg_attempt']:.2f>
Mar 20 21:23:53 ubuntu-2gb-nyc2-01 python[2449417]: AttributeError: 'NoneType' object has no attribute 'mention'
```

**Comment by jakehlee** [comment]
closed by [da70d7d](https://github.com/jakehlee/JDG-Cogs-V3/commit/da70d7da424cb09406183a524b569c083c2cbaa5)
