### ISSUE TITLE
Not compatible with v3.5 redbot

### ISSUE THREAD

**Issue by Ginpachi98** [jakehlee/JDG-Cogs-V3#15]
It throws this error when loaded, which is problem with many other cogs.

"Exception during loading of package
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression
"

**Comment by Ginpachi98** [comment]
It works with this __init__.py:


```
from .wordle import Wordle

async def setup(bot):
    cog = Wordle(bot)
    await bot.add_cog(cog)
```
